# Generated by Django 5.2.13 on 2026-10-05 12:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "chat_service_id",
                    models.CharField(
                        help_text="Identifier of the conversation on its chat service.",
                        max_length=255,
                        unique=True,
                        verbose_name="chat service id",
                    ),
                ),
                (
                    "meet_room_id",
                    models.UUIDField(
                        help_text="Identifier of the room on Visio.",
                        unique=True,
                        verbose_name="Visio room id",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="url")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visio room",
                "verbose_name_plural": "Visio rooms",
                "db_table": "hub_meet_room",
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="started at"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time at which Visio reported the call as started.",
                        null=True,
                        verbose_name="confirmed at",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ended at"
                    ),
                ),
                (
                    "meet_call_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of the call on Visio.",
                        max_length=255,
                        null=True,
                        verbose_name="Visio call id",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="started by",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="core.meetroom",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "call",
                "verbose_name_plural": "calls",
                "db_table": "hub_call",
                "ordering": ("-started_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("room",),
                        name="unique_ongoing_call_per_room",
                    ),
                    models.UniqueConstraint(
                        fields=("room", "meet_call_id"),
                        name="unique_meet_call_id_per_room",
                    ),
                ],
            },
        ),
    ]
